// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {conntrack} from '../models';

export function GetConnections():Promise<Array<conntrack.Connection>>;
