// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {conntrack} from '../models';
import {config} from '../models';

export function CheckUpdate(arg1:boolean):Promise<Record<string, any>>;

export function DoUpdate(arg1:boolean,arg2:string,arg3:string):Promise<void>;

export function GetConnections():Promise<Array<conntrack.Connection>>;

export function GetSettings():Promise<config.Config>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function GetVersion():Promise<string>;

export function GetRuntimeLogs(arg1:number):Promise<Array<string>>;

export function GetProbeNodeInfo(arg1:boolean):Promise<Record<string, any>>;
