// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function DoUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['DoUpdate'](arg1, arg2, arg3);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetRuntimeLogs(arg1) {
  return window['go']['main']['App']['GetRuntimeLogs'](arg1);
}
